### ISSUE TITLE
Set up servod to run at startup time

### ISSUE THREAD

**Issue by CairaLynn** [Quadforge/guPiBlaster2#4]
I was wondering if you have any tips on how to do this. Also, I'm not sure what the command is to start running servoblaster.

**Comment by CairaLynn** [comment]
@codyfinn

**Comment by codyfinn** [comment]
This can be done by editing the startup script. You should create a file at "/etc/init.d/" name it something like servod and inside it just type the command you normally use to launch the daemon.
